# Generated by Django 5.0.6 on 2024-10-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_theme',
            field=models.CharField(blank=True, choices=[('empowerment', 'Empowerment'), ('entrepreneurship', 'Entrepreneurship'), ('marketing', 'Marketing'), ('craftsmanship', 'Craftsmanship'), ('digital_skills', 'Digital Skills')], max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('bootcamp', 'Bootcamp'), ('conference', 'Conference'), ('bazaar', 'Bazaar'), ('networking', 'Networking')], max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.CharField(blank=True, choices=[('artisans_and_craftswomen', 'Artisans and Craftswomen'), ('aspiring_entrepreneurs', 'Aspiring Entrepreneurs'), ('small_business_owners', 'Small Business Owners'), ('students_and_young_professionals', 'Students and Young Professionals'), ('community_leaders_and_activists', 'Community Leaders and Activists'), ('hobbyists_and_creatives', 'Hobbyists and Creatives'), ('mentors_and_educators', 'Mentors and Educators'), ('nonprofit_organizations', 'Nonprofit Organizations and NGOs')], max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
