# Generated by Django 5.0.6 on 2024-10-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_theme_event_event_type_event_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_theme',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
    ]
