# Generated by Django 5.0.6 on 2024-10-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_theme_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
