# Generated by Django 5.0.6 on 2024-10-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dynamic_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
