# Generated by Django 5.0.6 on 2024-10-28 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_dynamic_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dynamic_price',
        ),
    ]
