# Generated by Django 5.0.6 on 2024-10-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0002_category_image'),
        ('paiement', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
