# Generated by Django 5.0.6 on 2024-10-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
