# Generated by Django 5.0.6 on 2024-10-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_addresse_user_bio_user_profile_photo_user_tel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brand_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='brand_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='brand_rne_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RNE Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='request_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
