# Generated by Django 5.0.6 on 2024-10-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_brand_description_user_brand_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='request_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
