# Generated by Django 5.0.6 on 2024-10-10 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée')], default='basse', max_length=50),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('resolue', 'Résolue'), ('refusee', 'Refusée')], default='en_attente', max_length=50),
        ),
        migrations.AddField(
            model_name='reponse',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponse',
            name='est_approuvee',
            field=models.BooleanField(default=False),
        ),
    ]
